"""Maintain parallel everyday constructions in the native English and SMG grammars.

Only the marked extension sections are generated. Existing reviewed clitic,
PCC, relative and word-order programs stay in their maintained files.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src/dynamicsyntax/grammars"
MARKER = "// Everyday construction extensions. Generated by scripts/build_everyday_extensions.py."


def prefix(path):
    return path.read_text().split(MARKER)[0].rstrip()


def write(path, body):
    path.write_text(prefix(path) + "\n\n" + MARKER + "\n\n" + body.strip() + "\n")


def block(text, title):
    start = 0 if text.startswith(title + "(") else text.index("\n" + title + "(") + 1
    return text[start:].split("\n\n")[0]


def build(backend):
    entity, prop, cn = ("object", "Prop", "CN") if backend == "mltt" else ("e", "t", "cn")
    b = backend
    vp = f"arrow({entity},{prop})"
    degree = rf"""degree(PRED)
IF ?Ty({b}:{vp})
   [+COPULA]
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN make(\/1)
   go(\/1)
   put(Ty({b}:arrow({vp},{vp})))
   put(Fo({b}:lam(P,{vp},lam(x,{entity},PRED(P(x))))))
   go(/\1)
   make(\/0)
   go(\/0)
   put(?Ty({b}:{vp}))
   put([+COPULA])
ELSE abort

predicative-adjective(PRED)
IF ?Ty({b}:{vp})
   [+COPULA]
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN put(Ty({b}:{vp}))
   put(Fo({b}:lam(x,{entity},PRED(x))))
ELSE abort"""
    en = ROOT / f"2026-english-{b}"
    actions = prefix(en / "lexical-actions.txt")
    if b == "mltt":
        adjective = block(actions, "adjective")
        actions = actions.replace(adjective, adjective.replace("sigma(x,A,PRED(x))", "refine(A,PRED)"))
    # Plural morphology is licensed by the quantifier, not by pretending a
    # plural surface is an ordinary singular CN. Propagate the gate through
    # intersective adjectives so "all black dogs" keeps the same restriction.
    plurals = []
    for template in ("noun", "adjective"):
        original = block(actions, template).replace("   ¬[+DISTRIBUTIVE-PLURAL]\n", "")
        singular = original.replace("\n   ¬<\\/0>Ex.x", "\n   ¬[+DISTRIBUTIVE-PLURAL]\n   ¬<\\/0>Ex.x", 1)
        actions = actions.replace(block(actions, template), singular)
        plural = original.replace(template + "(", "plural-" + template + "(", 1).replace("\n   ¬<\\/0>Ex.x", "\n   [+DISTRIBUTIVE-PLURAL]\n   ¬<\\/0>Ex.x", 1)
        if template == "adjective":
            plural = plural.replace("\nELSE abort", "\n   put([+DISTRIBUTIVE-PLURAL])\nELSE abort")
        contextual = plural.replace("plural-" + template + "(", "contextual-plural-" + template + "(", 1)
        contextual = contextual.replace("   [+DISTRIBUTIVE-PLURAL]", "   [+DISTRIBUTIVE-PLURAL]\n   [+CONTEXT-ALL]\n   ¬?[+ALL-ARTICLE]", 1)
        plural = plural.replace("   [+DISTRIBUTIVE-PLURAL]", "   [+DISTRIBUTIVE-PLURAL]\n   ¬[+CONTEXT-ALL]", 1)
        if template == "adjective":
            contextual = contextual.replace("\nELSE abort", "\n   put([+CONTEXT-ALL])\nELSE abort")
        elif b == "mltt":
            contextual = contextual.replace("Fo(mltt:NAME)", "Fo(mltt:sigma(x,NAME,in_context(x)))")
        else:
            contextual = contextual.replace("cn(x,NAME(x))", "cn(x,and(NAME(x),in_context(x)))")
        plurals.extend([plural, contextual])
    if "   ¬[+MODAL]\n" not in block(actions, "negative"):
        actions = actions.replace(block(actions, "negative"), block(actions, "negative").replace("   ?[+BARE-VERB]", "   ?[+BARE-VERB]\n   ¬[+MODAL]"))
    (en / "lexical-actions.txt").write_text(actions + "\n")
    all_plural = block(actions, "universal").replace("universal(", "all-plural(", 1)
    if b == "classical":
        all_plural = all_plural.replace("arrow(cn,e)", "arrow(cn,arrow(arrow(e,t),t))")
        all_plural = all_plural.replace("lam(P,cn,choice_tau(P))", "lam(P,cn,lam(Q,arrow(e,t),forall(x,e,implies(predication(P,x),Q(x)))))")
    all_plural = all_plural.replace("\nELSE abort", "\n   put([+DISTRIBUTIVE-PLURAL])\nELSE abort")
    all_contextual = all_plural.replace("all-plural(", "all-contextual(", 1).replace("\nELSE abort", "\n   put([+CONTEXT-ALL])\n   put(?[+ALL-ARTICLE])\nELSE abort")
    all_article = """all-article(UNUSED)
IF ?[+ALL-ARTICLE]
   [+DISTRIBUTIVE-PLURAL]
THEN delete(?[+ALL-ARTICLE])
ELSE abort"""
    definite = block(actions, "indef").replace("indef(", "definite(", 1)
    definite = definite.replace("sigma(x,A,top)", "definite(A)").replace("choice_eps(P)", "choice_iota(P)")
    copula_adj = rf"""copula-adjective(UNUSED)
IF ?Ty({b}:{vp})
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
   ¬?[+BARE-VERB]
   ¬[+COPULA]
THEN put([+COPULA])
ELSE abort"""
    pronouns = []
    for position in ("subject", "object", "any"):
        guard = f"   {'¬' if position == 'object' else ''}</\\0>?Ty({b}:{prop})\n" if position != "any" else ""
        pronouns.append(rf"""pronoun-{position}(REF,SORT)
IF ?Ty({b}:{entity})
{guard}   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN semantic-pronoun(REF,SORT)
ELSE abort""")
    cop_neg = rf"""copula-negative-nominal(UNUSED)
IF ?Ty({b}:{cn})
   ?[+PREDICATIVE-ARTICLE]
   ¬</\0></\1>?[+NEG]
THEN go(/\0)
   go(/\1)
   put(?[+NEG])
   go(\/1)
   go(\/0)
ELSE abort

copula-negative-adjective(UNUSED)
IF ?Ty({b}:{vp})
   [+COPULA]
   </\1>?Ty({b}:{prop})
   ¬</\1>?[+NEG]
THEN go(/\1)
   put(?[+NEG])
   go(\/1)
ELSE abort"""
    write(en / "lexical-actions.txt", "\n\n".join([definite, copula_adj, degree, cop_neg, *pronouns, all_plural, all_contextual, all_article, *plurals]))
    extra = ["all all-plural none", "all all-contextual none", "the all-article none", "the definite none", "each universal none", "some indef none", "did aux-do none", "very degree very"]
    extra += [f"{word} copula-adjective none" for word in ("am", "is", "are", "was", "were")]
    extra += [f"{word} copula none" for word in ("was", "were")]
    extra += ["not copula-negative-nominal none", "not copula-negative-adjective none"]
    extra += ["me pronoun-object speaker human", "he pronoun-subject him human", "she pronoun-subject her human", "him pronoun-object him human", "her pronoun-object her human", "it pronoun-any it object", "we pronoun-subject we human", "us pronoun-object we human", "they pronoun-subject them human", "them pronoun-object them human"]
    lexicon_path = en / "lexicon.txt"
    lexicon_path.write_text(prefix(lexicon_path).replace("you proper you human", "you pronoun-any hearer human") + "\n")
    for line in prefix(en / "lexicon.txt").splitlines():
        fields = line.split()
        if len(fields) > 2 and fields[1].endswith("-base"):
            fields[1] = fields[1][:-5]
            finite = " ".join(fields)
            if finite not in prefix(en / "lexicon.txt").splitlines():
                extra.append(finite)
        if len(fields) > 2 and fields[1] == "adjective":
            extra.append(f"{fields[0]} predicative-adjective {fields[2]}")
            extra.append(f"{fields[0]} plural-adjective {fields[2]}")
            extra.append(f"{fields[0]} contextual-plural-adjective {fields[2]}")
    write(en / "lexicon.txt", "\n".join(extra))
    profile = json.loads((en / "semantics.json").read_text())
    # Like selects entities, including books; its subject remains human.
    profile["predicates"]["like"] = ["human", "object"]
    profile["predicates"]["in_context"] = ["object"]
    path = en / "lexicon.txt"
    path.write_text(path.read_text().replace("like human human", "like human object"))
    profile["modifiers"]["very"] = ["Prop"]
    profile.setdefault("referents", {}).update({"john": {"gender": "masc", "number": "sg"}, "bill": {"gender": "masc", "number": "sg"}, "mary": {"gender": "fem", "number": "sg"}})
    (en / "semantics.json").write_text(json.dumps(profile, ensure_ascii=False, indent=2) + "\n")

    gr = ROOT / f"2026-smg-{b}"
    write(gr / "computational-actions.txt", rf"""merge-nominative
!completion
IF Ty(x)
   </\0>?Ty({b}:{prop})
   <Y>(?Ex.Tn(x) & Case(nom) & </\*>Ex.x)
   subsumes(Y)
THEN merge(Y)
   go(/\0)
ELSE abort""")
    gr_actions = prefix(gr / "lexical-actions.txt")
    subject = rf"""make(\/0)
   go(\/0)
   put(Ty({b}:{entity}))
   put(Fo(U_SUBJ))
   put(?Ex.Fo(x))
   put(Person(PERSON))
   put(Number(sg))
   go(/\0)
   make(\/1)
   go(\/1)"""
    copula_gr = rf"""copula(SUBJ,PERSON)
IF ?Ty({b}:{prop})
   ¬[+VERB]
   ¬[+NA]
   ¬[+FUT]
THEN put([+VERB])
   put(Mood(Ind))
   {subject}
   put(?Ty({b}:{vp}))
   put([+COPULA])
   gofirst(?Ty({b}:{prop}))
ELSE abort"""
    pred = "predication(NAME,x)" if b == "mltt" else "NAME(x)"
    noun_pred = rf"""nominal-predicate(NAME)
IF ?Ty({b}:{vp})
   [+COPULA]
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN put(Ty({b}:{vp}))
   put(Fo({b}:lam(x,{entity},{pred})))
ELSE abort

copular-article(UNUSED)
IF ?Ty({b}:{vp})
   [+COPULA]
   ¬[+ARTICLE]
THEN put([+ARTICLE])
ELSE abort"""
    intrans = rf"""verb-intransitive(PRED,SUBJ,PERSON)
IF ?Ty({b}:{prop})
   ¬[+VERB]
   ¬[+NA]
   ¬[+FUT]
THEN put([+VERB])
   put(Mood(Ind))
   {subject}
   put(Ty({b}:{vp}))
   put(Fo({b}:lam(x,{entity},PRED(x))))
   gofirst(?Ty({b}:{prop}))
ELSE abort"""
    pronoun = rf"""pronoun-nom(REF,PERSON)
IF ?Ty({b}:{entity})
   ¬Ex.Fo(x)
   ¬[+TOPIC]
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN put(Ty({b}:{entity}))
   put(Fo(U_REF))
   put(?Ex.Fo(x))
   put(Person(PERSON))
   put(Number(sg))
   put(Case(nom))
   put(?</\0>Ty({b}:{prop}))
   gofirst(?Ty({b}:{prop}))
ELSE abort"""
    indef = block(gr_actions, "indefinite-acc")
    definite_acc = indef.replace("indefinite-acc(", "definite-acc(", 1).replace("[+INDEF]", "[+DEFINITE]")
    definite_acc = definite_acc.replace("sigma(x,A,top)", "definite(A)").replace("choice_eps(P)", "choice_iota(P)")
    definite_nom = definite_acc.replace("definite-acc(", "definite-nom(", 1).replace("Case(acc)", "Case(nom)").replace(f"?Ty({b}:{vp})", f"?Ty({b}:{prop})").replace(f"? </\\0>Ty({b}:{vp})", f"? </\\0>Ty({b}:{prop})")
    definite_nom = definite_nom.replace(f"?</\\0>Ty({b}:{vp})", f"?</\\0>Ty({b}:{prop})")
    indefinite_nom = indef.replace("indefinite-acc(", "indefinite-nom(", 1).replace("Case(acc)", "Case(nom)").replace(f"?</\\0>Ty({b}:{vp})", f"?</\\0>Ty({b}:{prop})")
    common_noun = block(gr_actions, "noun-acc").replace("noun-acc(NAME,GENDER)", "common-noun(NAME,CASE,GENDER)").replace("Case(acc)", "Case(CASE)")
    common_noun = common_noun.replace("</\\0>Case(CASE)", "(Case(CASE) || </\\0>Case(CASE))").replace("</\\0>Gender(GENDER)", "(Gender(GENDER) || </\\0>Gender(GENDER))")
    write(gr / "lexical-actions.txt", "\n\n".join([copula_gr, noun_pred, degree, intrans, pronoun, definite_acc, definite_nom, indefinite_nom, common_noun]))
    rows = ["είμαι copula speaker 1", "είσαι copula hearer 2", "είναι copula pro 3", "εγώ pronoun-nom speaker 1", "εσύ pronoun-nom hearer 2", "αυτός pronoun-nom pro 3", "αυτή pronoun-nom her 3", "πολύ degree very"]
    for form, case, gender in [("ο", "nom", "m"), ("η", "nom", "f"), ("το", "nom", "neut"), ("τον", "acc", "m"), ("την", "acc", "f"), ("το", "acc", "neut")]:
        rows.append(f"{form} definite-{case} {gender}")
    rows += ["η article-name nom f", "τη article-name acc f", "την article-name acc f", "γιάννης proper-name-nom giannis m", "μαρία proper-name-nom maria f", "μαρία proper-name-acc maria f"]
    for form, case, gender in [("ένας", "nom", "m"), ("έναν", "acc", "m"), ("μια", "nom", "f"), ("μία", "nom", "f"), ("μια", "acc", "f"), ("μία", "acc", "f"), ("ένα", "nom", "neut")]:
        rows.append(f"{form} indefinite-{case} {gender}")
    for form in ("ένας", "μια", "μία", "ένα"):
        rows.append(f"{form} copular-article none")
    # Explicit singular inflections: nominative/accusative, semantic symbol, gender, parent.
    nouns = [
        ("άντρας", "άντρα", "man", "m", "human"),
        ("άνθρωπος", "άνθρωπο", "person", "m", "human"),
        ("γυναίκα", "γυναίκα", "woman", "f", "human"),
        ("γιατρός", "γιατρό", "doctor", "m", "human"),
        ("δάσκαλος", "δάσκαλο", "teacher", "m", "human"),
        ("δασκάλα", "δασκάλα", "female_teacher", "f", "human"),
        ("ασθενής", "ασθενή", "patient", "m", "human"),
        ("μαλάκας", "μαλάκα", "malakas", "m", "human"),
        ("παιδί", "παιδί", "child", "neut", "human"),
        ("σκύλος", "σκύλο", "dog", "m", "object"),
        ("γάτα", "γάτα", "cat", "f", "object"),
        ("βιβλίο", "βιβλίο", "book", "neut", "object"),
        ("γράμμα", "γράμμα", "letter", "neut", "object"),
        ("σπίτι", "σπίτι", "house", "neut", "object"),
        ("πάρκο", "πάρκο", "park", "neut", "object"),
    ]
    profile = json.loads((gr / "semantics.json").read_text())
    for nom, acc, symbol, gender, parent in nouns:
        rows.extend([f"{nom} common-noun {symbol} nom {gender}", f"{acc} common-noun {symbol} acc {gender}", f"{nom} nominal-predicate {symbol}"])
        profile["subtyping"][symbol] = [parent]
        if b == "classical":
            profile["predicates"][symbol] = ["object"]
    for forms, symbol in [("χαρούμενος χαρούμενη χαρούμενο", "happy"), ("καλός καλή καλό", "good"), ("κόκκινος κόκκινη κόκκινο", "red"), ("κουρασμένος κουρασμένη κουρασμένο", "tired")]:
        rows += [f"{form} predicative-adjective {symbol}" for form in forms.split()]
        profile["predicates"][symbol] = ["object"]
    for forms, symbol, transitive in [
        ("διαβάζω διαβάζεις διαβάζει", "read", True),
        ("ξέρω ξέρεις ξέρει", "know", True),
        ("αγαπώ αγαπάς αγαπάει", "love", True),
        ("εξετάζω εξετάζεις εξετάζει", "examine", True),
        ("γράφω γράφεις γράφει", "write", True),
        ("περπατάω περπατάς περπατάει", "walk", False),
        ("περπατώ περπατάς περπατά", "walk", False),
        ("τρέχω τρέχεις τρέχει", "run", False),
        ("κοιμάμαι κοιμάσαι κοιμάται", "sleep", False),
    ]:
        for person, (form, referent) in enumerate(zip(forms.split(), ("speaker", "hearer", "pro")), 1):
            line = f"{form} verb-finite {symbol} {referent} {person} sg" if transitive else f"{form} verb-intransitive {symbol} {referent} {person}"
            if line not in prefix(gr / "lexicon.txt").splitlines():
                rows.append(line)
        profile["predicates"][symbol] = ["object"] * (2 if transitive else 1)
    profile["constants"]["maria"] = "human"
    profile["referents"]["maria"] = {"person": 3, "gender": "fem", "number": "sg"}
    profile.setdefault("modifiers", {})["very"] = ["Prop"]
    write(gr / "lexicon.txt", "\n".join(dict.fromkeys(rows)))
    (gr / "semantics.json").write_text(json.dumps(profile, ensure_ascii=False, indent=2) + "\n")
    for language, root in (("en", en), ("el", gr)):
        open_text(root, b, language)
        from build_pp_extensions import extend
        extend(root, b, language)
        if language == "en":
            from build_dialogue_extensions import extend as dialogue_extensions
            dialogue_extensions(root, b)
        from build_causal_extensions import extend as causal_extensions
        causal_extensions(root, b, language)
        if language == "en":
            from build_nonrestrictive_extensions import extend as nonrestrictive_extensions
            nonrestrictive_extensions(root, b)


def open_text(root, b, language):
    """Reviewed construction families; shared syntax, explicit backend formulas."""
    entity, prop = ("object", "Prop") if b == "mltt" else ("e", "t")
    vp = f"arrow({entity},{prop})"
    blocks = [rf"""copular-location(PRED)
IF ?Ty({b}:{vp})
   [+COPULA]
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN make(\/1)
   go(\/1)
   put(Ty({b}:arrow({entity},{vp})))
   put(Fo({b}:lam(y,{entity},lam(x,{entity},PRED(x,y)))))
   go(/\1)
   make(\/0)
   go(\/0)
   put(?Ty({b}:{entity}))
ELSE abort

locative(PRED)
IF ?Ty({b}:{vp})
   [+COPULA]
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN put(Ty({b}:{vp}))
   put(Fo({b}:lam(x,{entity},PRED(x))))
ELSE abort

clause-and(UNUSED)
IF Ty({b}:{prop})
   complete
THEN semantic-coordinate
ELSE abort

clause-comma(UNUSED)
IF Ty({b}:{prop})
   complete
THEN do_nothing
ELSE abort"""]
    rows = [", clause-comma none", f"{'and' if language == 'en' else 'και'} clause-and none"]
    if language == "en":
        rows.append("and vp-and none")
        blocks.append(rf"""vp-and(UNUSED)
IF Ty({b}:{prop})
   complete
THEN go(\/1)
   semantic-vp-coordinate
ELSE abort""")
    locations = [("here", "here_location"), ("there", "there_location"), ("nearby", "nearby_location"), ("upstairs", "upstairs_location"), ("downstairs", "downstairs_location"), ("outside", "outside_location"), ("inside", "inside_location"), ("home", "home_location")] if language == "en" else [("εδώ", "here_location"), ("εκεί", "there_location"), ("κοντά", "nearby_location"), ("έξω", "outside_location"), ("μέσα", "inside_location"), ("πάνω", "upstairs_location"), ("κάτω", "downstairs_location")]
    preps = [("in", "located_in"), ("at", "located_at"), ("on", "located_on"), ("near", "located_near"), ("under", "located_under"), ("above", "located_above"), ("behind", "located_behind"), ("beside", "located_beside")] if language == "en" else [("σε", "located_at")]
    profile = json.loads((root / "semantics.json").read_text())
    modal_rules = []
    if language == "en":
        for word, operator in (("can", "possible"), ("could", "possible"), ("may", "permitted"), ("might", "possible"), ("must", "necessary"), ("should", "obligatory"), ("will", "future"), ("would", "conditional")):
            rows.append(f"{word} modal-{operator} none")
            profile["modifiers"][operator] = ["Prop"]
            profile["content_modifiers"] = sorted(set(profile.get("content_modifiers", [])) | {operator})
            blocks.append(rf"""modal-{operator}(UNUSED)
IF ?Ty({b}:{vp})
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
   ¬[+MODAL]
   ¬?[+BARE-VERB]
THEN put([+MODAL])
   put(?[+BARE-VERB])
   go(/\1)
   put(?[+MODAL-{operator.upper()}])
   go(\/1)
ELSE abort""")
            modal_rules.append(rf"""*modal-{operator}-completion
IF ?[+MODAL-{operator.upper()}]
   Ty({b}:{prop})
   ¬?Ty({b}:{prop})
THEN semantic-modal({operator})
   delete(?[+MODAL-{operator.upper()}])
ELSE abort""")
    for word, symbol in locations:
        rows.append(f"{word} locative {symbol}")
        profile["predicates"][symbol] = ["object"]
    for word, symbol in preps:
        rows.append(f"{word} copular-location {symbol}")
        profile["predicates"][symbol] = ["object", "object"]
    # Deictic predicates remain context-dependent; no place is silently invented.
    profile["interpretation_notes"] = ["Location predicates here/there/home depend on the utterance context; no geographic referent is resolved.", "Tense and full number agreement are not represented by this fragment.", "Positive English modals use explicit content operators (possible, permitted, necessary, obligatory, future, conditional); their modal axioms and negative scope readings are not supplied."]
    if language == "el":
        # Contracted σε + definite article consumes one surface word, while
        # constructing both the location relation and the definite DP subtree.
        location = block(blocks[0], "copular-location")
        definite = block((root / "lexical-actions.txt").read_text(), "definite-acc")
        body = definite.split("THEN ", 1)[1].rsplit("\nELSE abort", 1)[0]
        blocks.append(location.replace("copular-location(PRED)", "copular-location-article(PRED,GENDER)").replace("\nELSE abort", "\n   " + body + "\nELSE abort"))
        for form, gender in (("στο", "neut"), ("στον", "m"), ("στη", "f"), ("στην", "f")):
            rows.append(f"{form} copular-location-article located_at {gender}")
        cn = "CN" if b == "mltt" else "cn"
        adjbody = "sigma(x,A,PRED(x))" if b == "mltt" else "cn(cn_var(A),and(cn_body(A),PRED(cn_var(A))))"
        blocks.append(rf"""common-adjective(PRED,CASE,GENDER)
IF ?Ty({b}:{cn})
   (Case(CASE) || </\0>Case(CASE))
   (Gender(GENDER) || </\0>Gender(GENDER))
   ¬<\/0>Ex.x
   ¬<\/1>Ex.x
THEN make(\/1)
   go(\/1)
   put(Ty({b}:arrow({cn},{cn})))
   put(Fo({b}:lam(A,{cn},{adjbody})))
   go(/\1)
   make(\/0)
   go(\/0)
   put(?Ty({b}:{cn}))
   put(Case(CASE))
   put(Gender(GENDER))
ELSE abort""")
    # Coordination uses a LINK tree containing two actual clause derivations.
    computational = root / "computational-actions.txt"
    computational.write_text(computational.read_text().split("// Open text coordination.")[0].rstrip() + "\n")
    with computational.open("a") as file:
        file.write(rf"""

// Open text coordination.
*vp-coordinate-types
IF [+VP-COORD]
   <\/0>Ty(x)
   ¬<\/0>Ex.?x
THEN semantic-vp-coordinate-types
ELSE abort

*coordinate-completion
IF [+COORDINATED]
   Ty({b}:{prop})
   ¬Ex.?x
THEN semantic-coordinate-close
ELSE abort
""")
        if modal_rules:
            file.write("\n\n" + "\n\n".join(dict.fromkeys(modal_rules)) + "\n")
    with (root / "lexical-actions.txt").open("a") as file:
        file.write("\n\n" + "\n\n".join(dict.fromkeys(blocks)) + "\n")
    with (root / "lexicon.txt").open("a") as file:
        file.write("\n" + "\n".join(rows) + "\n")
    (root / "semantics.json").write_text(json.dumps(profile, ensure_ascii=False, indent=2) + "\n")


if __name__ == "__main__":
    for backend in ("classical", "mltt"):
        build(backend)
