"""Build the six small native Greek clitic grammars from shared DS programs.

Run after editing this file; generated grammars are packaged for ordinary icp use.
Position is licensed inside lexical IF triggers, never by a frontend filter.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src/dynamicsyntax/grammars"

LEXICA = {
    "smg": {
        "clitic(him)": "τον ton",
        "clitic(theme)": "το to",
        "finite(love,pro)": "αγαπά agapa",
        "finite(know,speaker)": "ξέρω ksero",
        "finite(write,pro)": "γράφει grafi",
        "dependent(write,pro)": "γράψει grapsi",
        "imperative(write,hearer)": "γράφε grafe γράψε grapse",
        "negative(x)": "δεν den",
        "subjunctive(x)": "να na",
    },
    "cypriot": {
        "clitic(him)": "τον ton",
        "clitic(theme)": "το to",
        "finite(know,speaker)": "ιξέρω iksero",
        "finite(write,pro)": "γράφει grafi",
        "dependent(write,pro)": "γράψει grapsi",
        "imperative(write,hearer)": "γράφε grafe γράψε grapse",
        "negative(x)": "εν en",
        "subjunctive(x)": "να na",
    },
    "pontic": {
        "clitic(him)": "ατον aton",
        "clitic(theme)": "ατο ato",
        "finite(know,speaker)": "εξέρ ekser ξέρ kser",
        "negative(x)": "κι ci",
    },
}

GATES = {
    "smg": r"([\/1+]?Ty(x) || Mood(Imp))",
    "cypriot": r"(([+PROCL] & [\/1+]?Ty(x)) || (¬[+PROCL] & <\/1+>Ty(x)))",
    "pontic": r"<\/1+>Ty(x)",
}


def rule(header, conditions, effects):
    return (
        header
        + "\nIF "
        + "\n   ".join(conditions)
        + "\nTHEN "
        + "\n   ".join(effects)
        + "\nELSE abort\n\n"
    )


def build(dialect, backend):
    if dialect in {"smg", "pontic"}:
        raise ValueError(f"{dialect} is hand-maintained; the fragment generator must not overwrite it")
    entity, proposition = ("e", "t") if backend == "classical" else ("object", "Prop")
    # The small fragment uses object arguments; lexical context supplies the
    # reference values. No claim to a discourse-resolution or PCC implementation.
    e, t = f"{backend}:{entity}", f"{backend}:{proposition}"
    vp = f"{backend}:arrow({entity},{proposition})"
    verbtype = f"{backend}:arrow({entity},arrow({entity},{proposition}))"
    formula = f"lam(y,{entity},lam(x,{entity},PRED(x,y)))"
    actions = (
        "// Generated by scripts/build_greek_fragments.py; see docs/design/greek-clitics.md.\n\n"
    )
    actions += rule(
        "clitic(REF)",
        [f"?Ty({t})", GATES[dialect], "¬[+CLITIC]"],
        [
            r"make(\/1)",
            r"go(\/1)",
            f"put(?Ty({vp}))",
            r"make(\/0)",
            r"go(\/0)",
            f"put(Ty({e}))",
            f"put(Fo({backend}:REF))",
            f"gofirst(?Ty({t}))",
            "put([+CLITIC])",
        ],
    )
    for mood in ("finite", "dependent", "imperative"):
        conditions = [f"?Ty({t})", "¬[+VERB]"]
        effects = []
        if mood == "imperative":
            conditions += [r"[\/+]?Ex.Tn(x)", "¬[+PROCL]"]
            effects += ["put(Mood(Imp))"]
        effects += [
            "put([+VERB])",
            r"make(\/0)",
            r"go(\/0)",
            f"put(Ty({e}))",
            f"put(Fo({backend}:SUBJECT))",
            r"go(/\0)",
            r"make(\/1)",
            r"go(\/1)",
            f"put(?Ty({vp}))",
            r"make(\/1)",
            r"go(\/1)",
            f"put(Ty({verbtype}))",
            f"put(Fo({backend}:{formula}))",
            r"go(/\1)",
            r"make(\/0)",
            r"go(\/0)",
            f"put(?Ty({e}))",
            f"gofirst(?Ty({t}))",
        ]
        for variant, guards, body in (
            ("plain", ["¬[+NEG]", "¬[+NA]"], "PRED(x,y)"),
            ("neg", ["[+NEG]"], "not(PRED(x,y))"),
            ("na", ["[+NA]"], "potential(PRED(x,y))"),
        ):
            if mood == "dependent" and variant != "na":
                continue
            actions += rule(
                f"{mood}-{variant}(PRED,SUBJECT)",
                conditions + guards,
                [effect.replace("PRED(x,y)", body) for effect in effects],
            )
    for template, feature in (("negative", "NEG"), ("subjunctive", "NA")):
        actions += rule(
            f"{template}(UNUSED)",
            [f"?Ty({t})", r"¬<\/+>Ex.x", "¬[+PROCL]"],
            [
                "put([+PROCL])",
                f"put([+{feature}])",
                # A fixed open subject slot blocks the bare-tree imperative trigger.
                # This is an explicitly reduced model of the thesis situation spine.
                r"make(\/0)",
                r"go(\/0)",
                f"put(?Ty({e}))",
                r"go(/\0)",
            ],
        )
    actions += rule("punctuation(UNUSED)", [f"Ty({t})", "complete"], ["do_nothing"])

    computational = (ROOT / f"2026-english-{backend}" / "computational-actions.txt").read_text()
    computational = computational[computational.index("anticipation0\n") :]
    computational = computational[: computational.index("anticipation-link\n")]
    lexicon = "// Greek spelling and ASCII transliteration aliases; finite vocabulary.\n"
    for template, forms in LEXICA[dialect].items():
        action, arguments = template[:-1].split("(")
        for word in forms.split():
            variants = (
                [f"{action}-{v}" for v in ("plain", "neg", "na")]
                if action in {"finite", "imperative"}
                else ["dependent-na"]
                if action == "dependent"
                else [action]
            )
            for variant in variants:
                lexicon += f"{word} {variant} {arguments.replace(',', ' ')}\n"
    for punctuation in (".", "!", "?", ";", ";"):
        lexicon += f"{punctuation} punctuation x\n"

    theory = {
        "backend": backend,
        "axiom": t,
        "subtyping": {"human": ["object"]},
        "constants": {
            "speaker": "human",
            "hearer": "human",
            "pro": "human",
            "him": "human",
            "theme": "object",
        },
        "predicates": {
            "know": ["object", "object"],
            "love": ["object", "object"],
            "write": ["object", "object"],
            "potential": ["Prop"],
        },
        "fragment": "greek-clitics",
        "dialect": dialect,
    }
    directory = ROOT / f"2026-{dialect}-{backend}"
    directory.mkdir(exist_ok=True)
    for filename, content in {
        "lexical-actions.txt": actions,
        "lexicon.txt": lexicon,
        "computational-actions.txt": computational,
        "lexical-macros.txt": "// This fragment uses primitive DS actions directly.\n",
        "semantics.json": json.dumps(theory, ensure_ascii=False, indent=2) + "\n",
    }.items():
        (directory / filename).write_text(content, encoding="utf-8")


if __name__ == "__main__":
    for dialect in ("cypriot",):
        for backend in ("classical", "mltt"):
            build(dialect, backend)
